wallpaper {
    monitor = eDP-3
    path = ~/.config/hypr/wallpapers/ship.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = ~/.config/hypr/wallpapers/ship.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpapers/ship.jpg
    fit_mode = cover
}

# ...